clear; close all;

STRAIN='EC1118'; % Select STRAIN : 'BMV', 'CR85' or 'EC1118'

%% Define inputs

inputs.pathd.results_folder='WineFermentation_hybrids_FINAL_AROMAS';
inputs.pathd.short_name=STRAIN;
inputs.pathd.runident='getsdata_testcode_run1';

%% ODE model

inputs.model.n_st=43;
inputs.model.n_stimulus=0;
inputs.model.st_names=char('X','YAN','Xv','Xcarb','Xprot','Glucose','Fructose','Ethanol','Glycerol',...
    'XmRNA','gene','Acetate','Succinate',...
    'Ala','Arg','Asp','Cys','Glu','Gln','Gly','His','Ile','Leu','Lys','Meth','NH4Cl','Phe',...
    'Ser','Thr','Try','Tyr','Val',...
    'EthylAcetate','IsobutylAcetate','IsoamylAcetate','Isobutanol','IsoamylAlcohol','PhenylEthylAcetate',...
    'BenzylAlcohol','PhenylEthanol',...
    'Lactate','Butanediol',...
    'Malate');

%20 21 22 23 24 26
DATA=importdata(fullfile(pwd,STRAIN,'parsmodel_hybrids_final.csv'),',');
inputs.model.par_names=char({DATA.textdata{2:end,1}}');
isOpt=DATA.data(:,end);inputs.model.par=DATA.data(:,1)';
inputs.model.n_par=length(inputs.model.par);

%% Model

modelEquations_YANC;

%% Parameter estimation
inputs.PEsol.id_global_theta=inputs.model.par_names(find(isOpt),:);
inputs.PEsol.global_theta_guess=DATA.data(find(isOpt),1)';
inputs.PEsol.global_theta_max=DATA.data(find(isOpt),3)';
inputs.PEsol.global_theta_min=DATA.data(find(isOpt),2)';

%% Error model
inputs.exps.data_type='real';
inputs.exps.noise_type='hetero_var';
inputs.PEsol.PEcost_type='llk'; %'llk';
inputs.PEsol.lsq_type='Q_expmax';
inputs.model.input_model_type='charmodelC';

%% Solver Settings ARM

inputs.nlpsol.nlpsolver='ess';                        % [] NLP solver: 
%                                                       % LOCAL: 'local_fmincon'|'local_n2fb'|'local_dn2fb'|'local_dhc'|
%                                                       %        'local_ipopt'|'local_solnp'|'local_nomad'||'local_nl2sol'
%                                                       %        'local_lsqnonlin'
%                                                       % MULTISTART:'multi_fmincon'|'multi_n2fb'|'multi_dn2fb'|'multi_dhc'|
%                                                       %            'multi_ipopt'|'multi_solnp'|'multi_nomad'|'multi_nl2sol'
%                                                       %            'multi_lsqnonlin'
%                                                       % GLOBAL: 'de'|'sres'
%                                                       % HYBRID: 'hyb_de_fmincon'|'hyb_de_n2fb'|'hyb_de_dn2fb'|'hyb_de_dhc'|'hyp_de_ipopt'|
%                                                       %         'hyb_de_solnp'|'hyb_de_nomad'|
%                                                       %         'hyb_sres_fmincon'|'hyb_sres_n2fb'|'hyb_sres_dn2fb'|'hyb_sres_dhc'|
%                                                       %         'hyp_sres_ipopt'|'hyb_sres_solnp'|'hyb_sres_nomad'
%                                                       % METAHEURISTICS:
%                                                       % 'ess' or 'eSS' (default)
%                                                       % Note that the corresponding defaults are in files: 
%                                                       % OPT_solvers\DE\de_options.m; OPT_solvers\SRES\sres_options.m; 
%                                                       % OPT_solvers\eSS_**\ess_options.m
%                                                       
inputs.nlpsol.eSS.log_var = [1:length(inputs.PEsol.global_theta_guess)];
inputs.nlpsol.eSS.maxeval = 100000;
inputs.nlpsol.eSS.maxtime =3*300;
inputs.nlpsol.eSS.local.solver = 'fminsearch';
inputs.nlpsol.eSS.local.finish = 'fminsearch';
inputs.nlpsol.multi_starts=200; 
inputs.nlpsol.multistart.maxtime=6*300;
inputs.nlpsol.multistart.maxeval=100000;


%% ODE settings
inputs.ivpsol.ivpsolver='cvodes';
inputs.ivpsol.senssolver='cvodes';
inputs.ivpsol.rtol=1.0D-7;
inputs.ivpsol.atol=1.0D-7;
inputs.ivpsol.ivp_maxnumsteps=1e4;

%% Experiments
bio_0=0.1*0.465;
inputs.exps.n_exp=1;
iexp=1;
load_data;

citrate = inputs.exps.exp_data{iexp}(:,10); error_citrate = inputs.exps.error_data{iexp}(:,10);
malate = inputs.exps.exp_data{iexp}(:,12);  error_malate = inputs.exps.error_data{iexp}(:,12);


% Initial conditions

Y_0=[bio_0 ...
     YAN(1) ...
     log10(inputs.exps.exp_data{iexp}(1,4))  ...
     bio_0*0.35 bio_0*0.4 ...
     inputs.exps.exp_data{iexp}(1,5) ...
     inputs.exps.exp_data{iexp}(1,6) ...
     inputs.exps.exp_data{iexp}(1,8) ...
     inputs.exps.exp_data{iexp}(1,7) ...
     bio_0*0.25 0 ...
     inputs.exps.exp_data{1}(1,9) ...
     inputs.exps.exp_data{1}(1,13) ...
     inputs.exps.exp_data{1}(1,16) ...
     inputs.exps.exp_data{1}(1,17) ...
     inputs.exps.exp_data{1}(1,18) ...
     inputs.exps.exp_data{1}(1,19) ...
     inputs.exps.exp_data{1}(1,20) ...
     inputs.exps.exp_data{1}(1,21) ...
     inputs.exps.exp_data{1}(1,22) ...
     inputs.exps.exp_data{1}(1,23) ...
     inputs.exps.exp_data{1}(1,24) ...
     inputs.exps.exp_data{1}(1,25) ...
     inputs.exps.exp_data{1}(1,26) ...
     inputs.exps.exp_data{1}(1,27) ...
     inputs.exps.exp_data{1}(1,28) ...
     inputs.exps.exp_data{1}(1,29) ...
     inputs.exps.exp_data{1}(1,31) ...
     inputs.exps.exp_data{1}(1,32) ...
     inputs.exps.exp_data{1}(1,33) ...
     inputs.exps.exp_data{1}(1,34) ...
     inputs.exps.exp_data{1}(1,35) ...
     0 0 0 0 0 0 0 0 ...
     0 0 ...
     malate(1)];
 
 %% Define Observable

inputs.exps.n_obs{iexp}=39;
inputs.exps.obs_names{iexp}=char('X_o','YAN_o','Xv_o','Glucose_o',...
    'Fructose_o','Ethanol_o','Glycerol_o','Acetate_o','Succinate_o',...
    'Ala_o','Arg_o','Asp_o','Cys_o','Glu_o','Gln_o','Gly_o',...
    'His_o','Ile_o','Leu_o','Lys_o','Meth_o',...
    'NH4Cl_o','Phe_o','Ser_o','Thr_o','Try_o','Tyr_o','Val_o',...
    'EthylAcetate_o','IsobutylAcetate_o','IsoamylAcetate_o','Isobutanol_o','IsoamylAlcohol_o',...
    'PhenylEthylAcetate_o','BenzylAlcohol_o','PhenylEthanol_o',...
    'Lactate_o','Butanediol_o',...
    'Malate_o');

inputs.exps.obs{iexp}=char('X_o=X','YAN_o=YAN','Xv_o=Xv',...
    'Glucose_o=Glucose;','Fructose_o=Fructose;','Ethanol_o=Ethanol',...
    'Glycerol_o=Glycerol','Acetate_o=Acetate','Succinate_o=Succinate',...
    'Ala_o=Ala','Arg_o=Arg','Asp_o=Asp','Cys_o=Cys','Glu_o=Glu','Gln_o=Gln','Gly_o=Gly',...
    'His_o=His','Ile_o=Ile','Leu_o=Leu','Lys_o=Lys','Meth_o=Meth',...
    'NH4Cl_o=NH4Cl','Phe_o=Phe','Ser_o=Ser','Thr_o=Thr','Try_o=Try',...
    'Tyr_o=Tyr','Val_o=Val',...
    'EthylAcetate_o=EthylAcetate','IsobutylAcetate_o=IsobutylAcetate','IsoamylAcetate_o=IsoamylAcetate','Isobutanol_o=Isobutanol',...
    'IsoamylAlcohol_o=IsoamylAlcohol','PhenylEthylAcetate_o=PhenylEthylAcetate',...
    'BenzylAlcohol_o=BenzylAlcohol','PhenylEthanol_o=PhenylEthanol',...
    'Lactate_o=Lactate','Butanediol_o=Butanediol',...
    'Malate_o=Malate');

inputs.exps.exp_y0{iexp}=Y_0;

data_CFU=inputs.exps.exp_data{1}(:,4); %Computing error in log10 CFU
error_CFU=inputs.exps.error_data{1}(:,4);%Computing error in log10 CFU
error_log_CFU=error_CFU./(log(10).*data_CFU);%Computing error in log10 CFU

dummy= nan(size(inputs.exps.exp_data{iexp}(:,1),1),1);
inputs.exps.exp_data{iexp}=[         ...
    inputs.exps.exp_data{iexp}(:,3)  ...
    YAN'                             ...
    log10(inputs.exps.exp_data{iexp}(:,4))  ...
    inputs.exps.exp_data{iexp}(:,5)  ...
    inputs.exps.exp_data{iexp}(:,6)  ...
    inputs.exps.exp_data{iexp}(:,8)  ...
    inputs.exps.exp_data{iexp}(:,7)  ...
    inputs.exps.exp_data{iexp}(:,9)  ...
    inputs.exps.exp_data{iexp}(:,13) ...
    inputs.exps.exp_data{iexp}(:,16) ...
    inputs.exps.exp_data{iexp}(:,17) ...
    inputs.exps.exp_data{iexp}(:,18) ...
    inputs.exps.exp_data{iexp}(:,19) ...
    inputs.exps.exp_data{iexp}(:,20) ...
    inputs.exps.exp_data{iexp}(:,21) ...
    inputs.exps.exp_data{iexp}(:,22) ...
    inputs.exps.exp_data{iexp}(:,23) ...
    inputs.exps.exp_data{iexp}(:,24) ...
    inputs.exps.exp_data{iexp}(:,25) ...
    inputs.exps.exp_data{iexp}(:,26) ...
    inputs.exps.exp_data{iexp}(:,27) ...
    inputs.exps.exp_data{iexp}(:,28) ...
    inputs.exps.exp_data{iexp}(:,29) ...
    inputs.exps.exp_data{iexp}(:,31) ...
    inputs.exps.exp_data{iexp}(:,32) ...
    inputs.exps.exp_data{iexp}(:,33) ...
    inputs.exps.exp_data{iexp}(:,34) ...
    inputs.exps.exp_data{iexp}(:,35) ...
    inputs.exps.exp_data{iexp}(:,36) ...
    inputs.exps.exp_data{iexp}(:,37) ...
    inputs.exps.exp_data{iexp}(:,38) ...
    inputs.exps.exp_data{iexp}(:,39) ...
    inputs.exps.exp_data{iexp}(:,40) ...
    inputs.exps.exp_data{iexp}(:,41) ...
    inputs.exps.exp_data{iexp}(:,42) ...
    inputs.exps.exp_data{iexp}(:,43) ...
    inputs.exps.exp_data{iexp}(:,14) ...
    inputs.exps.exp_data{iexp}(:,15) ...
    malate];


inputs.exps.error_data{iexp}=[         ...
    inputs.exps.error_data{iexp}(:,3)  ...
    YAN_error'                         ...
    error_log_CFU                      ...
    inputs.exps.error_data{iexp}(:,5)  ...
    inputs.exps.error_data{iexp}(:,6)  ...
    inputs.exps.error_data{iexp}(:,8)  ...
    inputs.exps.error_data{iexp}(:,7)  ...
    inputs.exps.error_data{iexp}(:,9)  ...
    inputs.exps.error_data{iexp}(:,13) ...
    inputs.exps.error_data{iexp}(:,16) ...
    inputs.exps.error_data{iexp}(:,17) ...
    inputs.exps.error_data{iexp}(:,18) ...
    inputs.exps.error_data{iexp}(:,19) ...
    inputs.exps.error_data{iexp}(:,20) ...
    inputs.exps.error_data{iexp}(:,21) ...
    inputs.exps.error_data{iexp}(:,22) ...
    inputs.exps.error_data{iexp}(:,23) ...
    inputs.exps.error_data{iexp}(:,24) ...
    inputs.exps.error_data{iexp}(:,25) ...
    inputs.exps.error_data{iexp}(:,26) ...
    inputs.exps.error_data{iexp}(:,27) ...
    inputs.exps.error_data{iexp}(:,28) ...
    inputs.exps.error_data{iexp}(:,29) ...
    inputs.exps.error_data{iexp}(:,31) ...
    inputs.exps.error_data{iexp}(:,32) ...
    inputs.exps.error_data{iexp}(:,33) ...
    inputs.exps.error_data{iexp}(:,34) ...
    inputs.exps.error_data{iexp}(:,35) ...
    inputs.exps.error_data{iexp}(:,36) ...
    inputs.exps.error_data{iexp}(:,37) ...
    inputs.exps.error_data{iexp}(:,38) ...
    inputs.exps.error_data{iexp}(:,39) ...
    inputs.exps.error_data{iexp}(:,40) ...
    inputs.exps.error_data{iexp}(:,41) ...
    inputs.exps.error_data{iexp}(:,42) ...
    inputs.exps.error_data{iexp}(:,43) ...
    inputs.exps.error_data{iexp}(:,14) ...
    inputs.exps.error_data{iexp}(:,15) ...
    error_malate];

inputs.exps.error_data{iexp}(isnan(inputs.exps.error_data{1}))=nan;
inputs.exps.error_data{iexp}(inputs.exps.error_data{iexp}==Inf)=nan;

ID_val = find(isnan(inputs.exps.exp_data{1}) ~= isnan(inputs.exps.error_data{1}));

inputs.exps.error_data{iexp}(ID_val)=0.05.*inputs.exps.exp_data{iexp}(ID_val);
inputs.exps.error_data{iexp}(inputs.exps.error_data{iexp}==0)=0.0005;

%% RUN AMIGO_SDATA or AMIGO_PE

AMIGO_Prep(inputs)
AMIGO_SData(inputs)
% AMIGO_PE(inputs)
